name: update README.md

on:
  push:
  workflow_dispatch:
  schedule:
    # "At 4:20 on every day-of-week from Monday through Friday."
    - cron: "20 4 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: omcdotsh
          author_email: macieiraoscar@icloud.com
          force: false
          signoff: false
          message: "memo: README.md updated by Gabot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop workflow
        if: always()
        run: exit 0
